version: "3.9"
services:
    board:
        container_name: bingo0
        restart: unless-stopped
        build: .
        ports:
            - "3001:3000"
    server:
        container_name: server0
        restart: unless-stopped
        build: ./server
        ports:
            - "5000:5000"
        depends_on:
            - db
        links:
            - db:db
    db:
        container_name: database0
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_DB=bingo
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5